defmodule OhioElixir.OGImage.HMAC do
  @moduledoc """
  HMAC-SHA256 signing and verification for OG image URLs.

  This prevents abuse of the /og endpoint by ensuring only URLs
  generated by our backend (with valid signatures) can generate images.
  """

  @doc """
  Signs OG image params with HMAC-SHA256.

  Returns a URL-safe base64-encoded signature.
  """
  def sign(params) when is_map(params) do
    canonical = canonicalize(params)

    :crypto.mac(:hmac, :sha256, secret(), canonical)
    |> Base.url_encode64(padding: false)
  end

  @doc """
  Verifies that a signature matches the given params.

  Uses constant-time comparison to prevent timing attacks.
  """
  def verify(params, signature) when is_map(params) and is_binary(signature) do
    expected = sign(params)
    Plug.Crypto.secure_compare(expected, signature)
  end

  def verify(_, _), do: false

  # Canonical string for signing: sorted key=value pairs joined with &
  defp canonicalize(params) do
    params
    |> Enum.reject(fn {_k, v} -> is_nil(v) or v == "" end)
    |> Enum.sort_by(fn {k, _v} -> to_string(k) end)
    |> Enum.map(fn {k, v} -> "#{k}=#{v}" end)
    |> Enum.join("&")
  end

  defp secret do
    Application.get_env(:ohio_elixir, :og_image)[:hmac_secret] ||
      raise "Missing :ohio_elixir, :og_image, :hmac_secret configuration"
  end
end
