defmodule OhioElixir.Repo.Migrations.AddEventsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:venues, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :website_url, :text
      add :notes, :text
      add :country, :text
      add :postal_code, :text
      add :state, :text
      add :city, :text
      add :address_line_2, :text
      add :address_line_1, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:users) do
      add :role, :text, null: false
    end

    create table(:events, primary_key: false) do
      add :venue_id, references(:venues, column: :id, name: "events_venue_id_fkey", type: :uuid)

      add :created_by_id,
          references(:users, column: :id, name: "events_created_by_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :capacity, :bigint
      add :meeting_url, :text
      add :timezone, :text, null: false
      add :ends_at, :utc_datetime
      add :starts_at, :utc_datetime, null: false
      add :format, :text, null: false
      add :status, :text, null: false
      add :description, :text
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:event_rsvps, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "event_rsvps_user_id_fkey", type: :uuid),
          null: false

      add :event_id,
          references(:events, column: :id, name: "event_rsvps_event_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :attended, :boolean
      add :notes, :text
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:event_rsvps, [:user_id, :event_id],
             name: "event_rsvps_unique_user_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(:event_rsvps, [:user_id, :event_id],
                     name: "event_rsvps_unique_user_event_index"
                   )

    drop constraint(:event_rsvps, "event_rsvps_event_id_fkey")

    drop constraint(:event_rsvps, "event_rsvps_user_id_fkey")

    drop table(:event_rsvps)

    drop constraint(:events, "events_created_by_id_fkey")

    drop constraint(:events, "events_venue_id_fkey")

    drop table(:events)

    alter table(:users) do
      remove :role
    end

    drop table(:venues)
  end
end
