defmodule OhioElixir.Repo.Migrations.AddAttendanceModeToRsvps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_rsvps) do
      add :attendance_mode, :text
    end
  end

  def down do
    alter table(:event_rsvps) do
      remove :attendance_mode
    end
  end
end