defmodule OhioElixir.Repo.Migrations.AddShortDescriptionToEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :short_description, :text
    end
  end

  def down do
    alter table(:events) do
      remove :short_description
    end
  end
end