defmodule OhioElixir.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :last_name, :text
      add :preferences, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:users) do
      remove :preferences
      remove :last_name
      remove :first_name
    end
  end
end